/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BButton: typeof import('bootstrap-vue-next')['BButton']
    BButtonGroup: typeof import('bootstrap-vue-next')['BButtonGroup']
    BCard: typeof import('bootstrap-vue-next')['BCard']
    BCardText: typeof import('bootstrap-vue-next')['BCardText']
    BCol: typeof import('bootstrap-vue-next')['BCol']
    BContainer: typeof import('bootstrap-vue-next')['BContainer']
    BDropdown: typeof import('bootstrap-vue-next')['BDropdown']
    BDropdownDivider: typeof import('bootstrap-vue-next')['BDropdownDivider']
    BDropdownItem: typeof import('bootstrap-vue-next')['BDropdownItem']
    BModal: typeof import('bootstrap-vue-next')['BModal']
    BNav: typeof import('bootstrap-vue-next')['BNav']
    BNavItem: typeof import('bootstrap-vue-next')['BNavItem']
    BOffcanvas: typeof import('bootstrap-vue-next')['BOffcanvas']
    BRow: typeof import('bootstrap-vue-next')['BRow']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    NavMenu: typeof import('./src/components/navMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    vBTooltip: typeof import('bootstrap-vue-next')['vBTooltip']
  }
}
